import * as yup from "yup";
export const ProductionSchema = yup.object().shape({
    id: yup.string().required(),
    barcode: yup.string().required(),
    createdTime: yup.date().required(),
    createdId: yup.string().required(),
    description: yup.string().notRequired(),
    expiryDate: yup.date().notRequired(),
    name: yup.string().required(),
    producedDate: yup.date().notRequired(),
    qrcode: yup.string().required(),
    qrcode2: yup.string().required(),
    quantityUnit: yup.string().notRequired(),
    salcode: yup.string().required(),
    sapcode: yup.string().required(),
    status: yup.string().notRequired(),
    updatedTime: yup.date().notRequired(),
    updatedId: yup.string().notRequired(),
    warrantyInMonths: yup.number().notRequired(),
    warrantyRemarks: yup.string().notRequired(),
    activatingPoint: yup.number().notRequired(),
    viewTimes: yup.number().notRequired(),
});
